# Welcome to Jekyll!
#

# Site settings
title: GalsTech
owner: GalsTech # or company name

languages: ['en', 'de']

first_published:  2017 # if migrating another site, the year of your first publish
email: info@galstech.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.galstech.org" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/galstech_
  github: https://github.com/galstech
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/GalsTech-1826572957654739/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

plugins:
- jekyll-sitemap
- jekyll-language-plugin

language_data: data.lang.%%
language_includes_dir: _i18n